apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: primeiro-pod
spec:
  containers:
    - name: container-pode-1
      image: nginx:lastest
      ports: 
        - containerPort: 80
      